import Link from "next/link";
import { FileText } from "lucide-react";
import { TopBar } from "@/components/layout/topbar";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SeverityPill } from "@/components/ui/severity-pill";
import { getOperationalFindings } from "@/lib/operational-data";
export const metadata = { title: "Relatórios" }; export const dynamic = "force-dynamic";
export default async function ReportsPage() { const findings = await getOperationalFindings(); const groups = Object.values(Object.groupBy(findings, (f) => f.assetName)); return <><TopBar title="Relatórios" subtitle="Resumo comercial baseado nos achados persistidos" /><main className="tactical-grid flex-1 overflow-y-auto"><div className="mx-auto max-w-[1600px] p-8">{groups.length === 0 ? <Card><CardContent><EmptyState title="Sem achados para relatar" description="Conclua um scan autorizado para gerar o resumo técnico e executivo." /></CardContent></Card> : <div className="grid gap-4 md:grid-cols-2">{groups.map((items) => { const report = items ?? []; const asset = report[0]?.assetName ?? "Ativo"; return <Card key={asset} interactive><CardHeader><CardTitle className="flex items-center gap-2 text-bone-white normal-case"><FileText className="size-4 text-prism-cyan" />{asset}</CardTitle><span className="text-xs text-graphite-veil">{report.length} achado(s)</span></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2">{report.slice(0,5).map((f) => <SeverityPill key={f.id} severity={f.severity}>{f.severity}</SeverityPill>)}</div><p className="text-xs text-fog-blue">Prioridade: {report[0]?.title}</p><Link href={`/findings/${report[0]?.id}`} className="text-micro-caps text-prism-cyan hover:text-bone-white">Abrir achado prioritário</Link></CardContent></Card>; })}</div>}</div></main></>; }
