import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { createClient } from "@/lib/supabase/server";
import type { LlmProviderId } from "@/types";
const IDS: LlmProviderId[] = ["gemini", "groq", "openrouter"];
function key() { const secret = process.env.LLM_KEY_ENCRYPTION_SECRET; if (!secret) throw new Error("Defina LLM_KEY_ENCRYPTION_SECRET no ambiente seguro do servidor antes de salvar chaves de IA."); return createHash("sha256").update(secret).digest(); }
async function context() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("Faça login para gerenciar chaves de IA."); const { data: membership, error } = await supabase.from("org_members").select("org_id").eq("user_id", user.id).limit(1).maybeSingle(); if (error) throw error; if (!membership) throw new Error("Usuário sem organização autorizada."); return { supabase, orgId: membership.org_id, userId: user.id }; }
export async function listStoredProviderIds(): Promise<LlmProviderId[]> { const { supabase } = await context(); const { data, error } = await supabase.from("llm_provider_keys").select("provider"); if (error) throw error; return (data ?? []).map((x) => x.provider).filter((id): id is LlmProviderId => IDS.includes(id as LlmProviderId)); }
export async function saveProviderKey(provider: LlmProviderId, apiKey: string) { if (!IDS.includes(provider)) throw new Error("Provedor de IA inválido."); if (apiKey.trim().length < 12) throw new Error("A chave informada parece inválida."); const { supabase, orgId, userId } = await context(); const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(), iv); const ciphertext = Buffer.concat([cipher.update(apiKey.trim(), "utf8"), cipher.final()]); const { error } = await supabase.from("llm_provider_keys").upsert({ org_id: orgId, provider, ciphertext: ciphertext.toString("base64"), iv: iv.toString("base64"), auth_tag: cipher.getAuthTag().toString("base64"), created_by: userId, updated_at: new Date().toISOString() }, { onConflict: "org_id,provider" }); if (error) throw error; }
export async function deleteProviderKey(provider: LlmProviderId) { const { supabase } = await context(); const { error } = await supabase.from("llm_provider_keys").delete().eq("provider", provider); if (error) throw error; }
export async function getStoredProviderKey(provider: LlmProviderId): Promise<string | undefined> { try { const { supabase } = await context(); const { data, error } = await supabase.from("llm_provider_keys").select("ciphertext, iv, auth_tag").eq("provider", provider).maybeSingle(); if (error) throw error; if (!data) return undefined; const decipher = createDecipheriv("aes-256-gcm", key(), Buffer.from(data.iv, "base64")); decipher.setAuthTag(Buffer.from(data.auth_tag, "base64")); return Buffer.concat([decipher.update(Buffer.from(data.ciphertext, "base64")), decipher.final()]).toString("utf8"); } catch { return undefined; } }
